### ISSUE TITLE
Raw selectors not working 

### ISSUE THREAD

**Issue by stooit** [salsadigitalauorg/merlin-framework#1]
```
---
domain: https://www2.health.vic.gov.au

urls:
  - /about/news-and-events/News/celebrating-victorias-seniors
  # ... etc

entity_type: basic_page
mappings:
  -
    field: title
    selector: "h1#phbody_1_ctl01_h1Title" # Works
    selector: "h1" # Doesn't work
    type: text
    processors:
      nl2br: { }
```

Cannot find h1
