### ISSUE TITLE
Error reporting when multple selectors are used is wrong

### ISSUE THREAD

**Issue by stooit** [salsadigitalauorg/merlin-framework#110]
**Describe the bug**
When using multiple selectors (first match > single field) the page is incorrectly tracked in the `error-not-found` report even if one of the selectors match

**Sample configuration**
```
---
domain: https://www.example.com

urls:
  - /about
  - /sports/rugby

entity_type: standard_page
mappings:
  -
    field: title
    selector:
      - '//div[@id="content"]//h1[1]'
      - '//div[@id="content"]//h2[1]'
      - '//div[@id="content"]//h3[1]'
```

**Expected behavior**
If _any_ of the selector matches are found the element should not appear in the 'not-found' report

**Screenshots**
none

**Additional context**
none
