### ISSUE TITLE
Strip tags doesn't remove tag contents

### ISSUE THREAD

**Issue by steveworley** [salsadigitalauorg/merlin-framework#2]
```
---
domain: https://trademinister.gov.au

urls:
  - /releases/Pages/2019/sb_mr_190607a.aspx

  -
    field: body
    type: long_text
    selector: "#main-content"
    processors:
      - processor: remove_empty_tags
      -
        processor: media
        type: image-fr-landing_page
        selector: img
        file: src
        name: alt
      -
        processor: convert_encoding
        to_encoding: HTML-ENTITIES
        from_encoding: UTF-8
      -
        processor: strip_tags
        allowed_tags: <h1><h2><h3><h4><h5><ul><ol><dl><dt><dd><li><p><a><strong><em><cite><blockquote><code><s><span><sup><sub><table><caption><tbody><thead><tfoot><th><td><tr><hr><pre><drupal-entity><br>
        remove_attr:
          - class
          - id
          - style
      - processor: whitespace
```
