### ISSUE TITLE
Media processor for documents example

### ISSUE THREAD

**Issue by stooit** [salsadigitalauorg/merlin-framework#39]
**Describe the bug**
The media processor indicates it supports xpath, however it does not appear to function as documented

**Sample configuration**
```
---
domain: https://www.inslm.gov.au

urls:
  - /submissions/statutory-deadline-reviews

entity_type: basic_page
mappings:
  -
    field: alias
    type: alias
  -
    field: title
    selector: //*[@id="page-title"]
    type: text
    processors:
      nl2br: { }
  -
    field: field_body
    selector: '//*[@class="grid-12 region region-content"]'
    type: long_text
    processors:
      -
        processor: media
        type: document-basic_page
        selector: //a[contains(@type, 'application/pdf')]
        file: ./@href
        name: ./text()
        xpath: true
        data_entity_embed_display: view_mode:media.embed
        data_embed_button: media_entity_embed
```

**Expected behavior**
A documents json file should be generated, with inline references replaced with media embed code.
