### ISSUE TITLE
Different data structure for xpath vs. standard selector

### ISSUE THREAD

**Issue by stooit** [salsadigitalauorg/merlin-framework#63]
**Describe the bug**
When using `long_text` the resulting data structure differs for xpath vs. non-xpath selectors.

The non-xpath selector result always appears in an array of results, whereas xpath returns a single object.

**Sample configuration**
XPath (returns object):
```
---
domain: https://www.chiefscientist.gov.au
urls:
  - /about/

entity_type: basic_page
mappings:
  - field: alias
    type: alias
  - field: field_body
    selector: "//*[@id='content']"
    type: long_text
```

Standard (returns arr):
```
---
domain: https://www.chiefscientist.gov.au
urls:
  - /about/

entity_type: basic_page
mappings:
  - field: alias
    type: alias
  - field: field_body
    selector: "#content"
    type: long_text
```

**Expected behavior**
The type should behave the same way (single object for a single result) for non-xpath selectors.

**Additional context**
This is important so migration plugins have standard data schemas to work with no matter what type of selector is applied
