### ISSUE TITLE
cURL error handling

### ISSUE THREAD

**Issue by steveworley** [salsadigitalauorg/merlin-framework#97]
**Describe the bug**
Sometimes a domain will fail validating with the local CA cert. We should look at ways that we can automate or provide resolution steps to users.

```
http://www.chiefscientist.gov.au/2016/07/article-top-victorian-gong-for-australias-chief-scientist-alan-finkel-
         herald-sun/ -- cURL error 60:  (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) 
```

**Sample configuration**
```
domain: http://www.chiefscientist.gov.au
urls:
  - /2016/07/article-top-victorian-gong-for-australias-chief-scientist-alan-finkel-herald-sun/

entity_type: custom_govcms_article
mappings:
  - field: alias
    type: alias
    processors:
      - processor: replace
        pattern: (\/$)
        replace: ''
```
